title: X-brewing
email: info@x-brewing.com
description: >
  X-brewing
baseurl: ""
url: "https://disjfa.github.io"

# Google
google_analytics: UA-83598448-1

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

source: site
host: 0.0.0.0

collections:
  beers:
    output: true
  locations:
    output: false

facebook_url: https://www.facebook.com/X-brewing-169771763610772/
untapped_url: https://untappd.com/Xbrewing
instagram_url: https://www.instagram.com/this.is.x.brewing/
